config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'parser#index'
  get 'parser/index'
  post 'parser/index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/parser_controller.rb
require 'mecab'

class ParserController < ApplicationController
  def index
    params.permit(:text)
    @text = params[:text]
    @spaced_text = nil
    if !@text.nil? and !@text.empty?
      @spaced_text = @text.split(/\n/).map {|s| MeCab::Tagger.new().parse(s).split(/\n/).map {|l| build_element(l)}}
    else
      @text = ""
    end
  end

  private
  def build_element(token)
    term, info = token.split(/\t/)
    stuff = []
    term = '' if term == 'EOS'
    if (info)
      stuff = info.split(/,/)
    end
      
      {
        :term => term,
        :pos => stuff.first
      }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parser_helper.rb
module ParserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tokenizer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  
<%= yield %>

</body>
</html>

app/views/parser/index.html.erb
<h1>Parse Text</h1>

<%= form_tag(parser_index_path, method: "post", class: "form") do %>
  <%= text_area_tag(:text, @text, placeholder: "Enter text here", class: "form-control") %>
  <%= submit_tag("Parse", class: "btn btn-primary") %>
<% end %>

<% if @spaced_text %>
<pre id="spaced-text"><%  @spaced_text.each do |l| %><% l.each do |t| %><span class="<%= t[:pos] %>"><%= t[:term] %></span>&nbsp;<% end %><br><% end %></pre>
<% end %>